module BrandDev
  module Models
    type brand_prefetch_by_email_params =
      { email: String, timeout_ms: Integer }
      & BrandDev::Internal::Type::request_parameters

    class BrandPrefetchByEmailParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor email: String

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        email: String,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        email: String,
        timeout_ms: Integer,
        request_options: BrandDev::RequestOptions
      }
    end
  end
end
