module BrandDev
  module Models
    type brand_web_scrape_sitemap_params =
      { domain: String, max_links: Integer, url_regex: String }
      & BrandDev::Internal::Type::request_parameters

    class BrandWebScrapeSitemapParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_reader max_links: Integer?

      def max_links=: (Integer) -> Integer

      attr_reader url_regex: String?

      def url_regex=: (String) -> String

      def initialize: (
        domain: String,
        ?max_links: Integer,
        ?url_regex: String,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        max_links: Integer,
        url_regex: String,
        request_options: BrandDev::RequestOptions
      }
    end
  end
end
