module BrandDev
  module Models
    type brand_retrieve_params =
      {
        domain: String,
        force_language: BrandDev::Models::BrandRetrieveParams::force_language,
        max_speed: bool,
        timeout_ms: Integer
      }
      & BrandDev::Internal::Type::request_parameters

    class BrandRetrieveParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_reader force_language: BrandDev::Models::BrandRetrieveParams::force_language?

      def force_language=: (
        BrandDev::Models::BrandRetrieveParams::force_language
      ) -> BrandDev::Models::BrandRetrieveParams::force_language

      attr_reader max_speed: bool?

      def max_speed=: (bool) -> bool

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        domain: String,
        ?force_language: BrandDev::Models::BrandRetrieveParams::force_language,
        ?max_speed: bool,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        force_language: BrandDev::Models::BrandRetrieveParams::force_language,
        max_speed: bool,
        timeout_ms: Integer,
        request_options: BrandDev::RequestOptions
      }

      type force_language =
        :afrikaans
        | :albanian
        | :amharic
        | :arabic
        | :armenian
        | :assamese
        | :aymara
        | :azeri
        | :basque
        | :belarusian
        | :bengali
        | :bosnian
        | :bulgarian
        | :burmese
        | :cantonese
        | :catalan
        | :cebuano
        | :chinese
        | :corsican
        | :croatian
        | :czech
        | :danish
        | :dutch
        | :english
        | :esperanto
        | :estonian
        | :farsi
        | :fijian
        | :finnish
        | :french
        | :galician
        | :georgian
        | :german
        | :greek
        | :guarani
        | :gujarati
        | :"haitian-creole"
        | :hausa
        | :hawaiian
        | :hebrew
        | :hindi
        | :hmong
        | :hungarian
        | :icelandic
        | :igbo
        | :indonesian
        | :irish
        | :italian
        | :japanese
        | :javanese
        | :kannada
        | :kazakh
        | :khmer
        | :kinyarwanda
        | :korean
        | :kurdish
        | :kyrgyz
        | :lao
        | :latin
        | :latvian
        | :lingala
        | :lithuanian
        | :luxembourgish
        | :macedonian
        | :malagasy
        | :malay
        | :malayalam
        | :maltese
        | :maori
        | :marathi
        | :mongolian
        | :nepali
        | :norwegian
        | :odia
        | :oromo
        | :pashto
        | :pidgin
        | :polish
        | :portuguese
        | :punjabi
        | :quechua
        | :romanian
        | :russian
        | :samoan
        | :"scottish-gaelic"
        | :serbian
        | :sesotho
        | :shona
        | :sindhi
        | :sinhala
        | :slovak
        | :slovene
        | :somali
        | :spanish
        | :sundanese
        | :swahili
        | :swedish
        | :tagalog
        | :tajik
        | :tamil
        | :tatar
        | :telugu
        | :thai
        | :tibetan
        | :tigrinya
        | :tongan
        | :tswana
        | :turkish
        | :turkmen
        | :ukrainian
        | :urdu
        | :uyghur
        | :uzbek
        | :vietnamese
        | :welsh
        | :wolof
        | :xhosa
        | :yiddish
        | :yoruba
        | :zulu

      module ForceLanguage
        extend BrandDev::Internal::Type::Enum

        AFRIKAANS: :afrikaans
        ALBANIAN: :albanian
        AMHARIC: :amharic
        ARABIC: :arabic
        ARMENIAN: :armenian
        ASSAMESE: :assamese
        AYMARA: :aymara
        AZERI: :azeri
        BASQUE: :basque
        BELARUSIAN: :belarusian
        BENGALI: :bengali
        BOSNIAN: :bosnian
        BULGARIAN: :bulgarian
        BURMESE: :burmese
        CANTONESE: :cantonese
        CATALAN: :catalan
        CEBUANO: :cebuano
        CHINESE: :chinese
        CORSICAN: :corsican
        CROATIAN: :croatian
        CZECH: :czech
        DANISH: :danish
        DUTCH: :dutch
        ENGLISH: :english
        ESPERANTO: :esperanto
        ESTONIAN: :estonian
        FARSI: :farsi
        FIJIAN: :fijian
        FINNISH: :finnish
        FRENCH: :french
        GALICIAN: :galician
        GEORGIAN: :georgian
        GERMAN: :german
        GREEK: :greek
        GUARANI: :guarani
        GUJARATI: :gujarati
        HAITIAN_CREOLE: :"haitian-creole"
        HAUSA: :hausa
        HAWAIIAN: :hawaiian
        HEBREW: :hebrew
        HINDI: :hindi
        HMONG: :hmong
        HUNGARIAN: :hungarian
        ICELANDIC: :icelandic
        IGBO: :igbo
        INDONESIAN: :indonesian
        IRISH: :irish
        ITALIAN: :italian
        JAPANESE: :japanese
        JAVANESE: :javanese
        KANNADA: :kannada
        KAZAKH: :kazakh
        KHMER: :khmer
        KINYARWANDA: :kinyarwanda
        KOREAN: :korean
        KURDISH: :kurdish
        KYRGYZ: :kyrgyz
        LAO: :lao
        LATIN: :latin
        LATVIAN: :latvian
        LINGALA: :lingala
        LITHUANIAN: :lithuanian
        LUXEMBOURGISH: :luxembourgish
        MACEDONIAN: :macedonian
        MALAGASY: :malagasy
        MALAY: :malay
        MALAYALAM: :malayalam
        MALTESE: :maltese
        MAORI: :maori
        MARATHI: :marathi
        MONGOLIAN: :mongolian
        NEPALI: :nepali
        NORWEGIAN: :norwegian
        ODIA: :odia
        OROMO: :oromo
        PASHTO: :pashto
        PIDGIN: :pidgin
        POLISH: :polish
        PORTUGUESE: :portuguese
        PUNJABI: :punjabi
        QUECHUA: :quechua
        ROMANIAN: :romanian
        RUSSIAN: :russian
        SAMOAN: :samoan
        SCOTTISH_GAELIC: :"scottish-gaelic"
        SERBIAN: :serbian
        SESOTHO: :sesotho
        SHONA: :shona
        SINDHI: :sindhi
        SINHALA: :sinhala
        SLOVAK: :slovak
        SLOVENE: :slovene
        SOMALI: :somali
        SPANISH: :spanish
        SUNDANESE: :sundanese
        SWAHILI: :swahili
        SWEDISH: :swedish
        TAGALOG: :tagalog
        TAJIK: :tajik
        TAMIL: :tamil
        TATAR: :tatar
        TELUGU: :telugu
        THAI: :thai
        TIBETAN: :tibetan
        TIGRINYA: :tigrinya
        TONGAN: :tongan
        TSWANA: :tswana
        TURKISH: :turkish
        TURKMEN: :turkmen
        UKRAINIAN: :ukrainian
        URDU: :urdu
        UYGHUR: :uyghur
        UZBEK: :uzbek
        VIETNAMESE: :vietnamese
        WELSH: :welsh
        WOLOF: :wolof
        XHOSA: :xhosa
        YIDDISH: :yiddish
        YORUBA: :yoruba
        ZULU: :zulu

        def self?.values: -> ::Array[BrandDev::Models::BrandRetrieveParams::force_language]
      end
    end
  end
end
