module BrandDev
  module Models
    type brand_web_scrape_md_params =
      {
        url: String,
        include_images: bool,
        include_links: bool,
        max_age_ms: Integer,
        :shorten_base64_images => bool,
        use_main_content_only: bool
      }
      & BrandDev::Internal::Type::request_parameters

    class BrandWebScrapeMdParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor url: String

      attr_reader include_images: bool?

      def include_images=: (bool) -> bool

      attr_reader include_links: bool?

      def include_links=: (bool) -> bool

      attr_reader max_age_ms: Integer?

      def max_age_ms=: (Integer) -> Integer

      attr_reader shorten_base64_images: bool?

      def shorten_base64_images=: (bool) -> bool

      attr_reader use_main_content_only: bool?

      def use_main_content_only=: (bool) -> bool

      def initialize: (
        url: String,
        ?include_images: bool,
        ?include_links: bool,
        ?max_age_ms: Integer,
        ?shorten_base64_images: bool,
        ?use_main_content_only: bool,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        include_images: bool,
        include_links: bool,
        max_age_ms: Integer,
        :shorten_base64_images => bool,
        use_main_content_only: bool,
        request_options: BrandDev::RequestOptions
      }
    end
  end
end
