module BrandDev
  module Models
    type brand_retrieve_by_ticker_params =
      {
        ticker: String,
        force_language: BrandDev::Models::BrandRetrieveByTickerParams::force_language,
        max_speed: bool,
        ticker_exchange: BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange,
        timeout_ms: Integer
      }
      & BrandDev::Internal::Type::request_parameters

    class BrandRetrieveByTickerParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor ticker: String

      attr_reader force_language: BrandDev::Models::BrandRetrieveByTickerParams::force_language?

      def force_language=: (
        BrandDev::Models::BrandRetrieveByTickerParams::force_language
      ) -> BrandDev::Models::BrandRetrieveByTickerParams::force_language

      attr_reader max_speed: bool?

      def max_speed=: (bool) -> bool

      attr_reader ticker_exchange: BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange?

      def ticker_exchange=: (
        BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange
      ) -> BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        ticker: String,
        ?force_language: BrandDev::Models::BrandRetrieveByTickerParams::force_language,
        ?max_speed: bool,
        ?ticker_exchange: BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        ticker: String,
        force_language: BrandDev::Models::BrandRetrieveByTickerParams::force_language,
        max_speed: bool,
        ticker_exchange: BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange,
        timeout_ms: Integer,
        request_options: BrandDev::RequestOptions
      }

      type force_language =
        :afrikaans
        | :albanian
        | :amharic
        | :arabic
        | :armenian
        | :assamese
        | :aymara
        | :azeri
        | :basque
        | :belarusian
        | :bengali
        | :bosnian
        | :bulgarian
        | :burmese
        | :cantonese
        | :catalan
        | :cebuano
        | :chinese
        | :corsican
        | :croatian
        | :czech
        | :danish
        | :dutch
        | :english
        | :esperanto
        | :estonian
        | :farsi
        | :fijian
        | :finnish
        | :french
        | :galician
        | :georgian
        | :german
        | :greek
        | :guarani
        | :gujarati
        | :"haitian-creole"
        | :hausa
        | :hawaiian
        | :hebrew
        | :hindi
        | :hmong
        | :hungarian
        | :icelandic
        | :igbo
        | :indonesian
        | :irish
        | :italian
        | :japanese
        | :javanese
        | :kannada
        | :kazakh
        | :khmer
        | :kinyarwanda
        | :korean
        | :kurdish
        | :kyrgyz
        | :lao
        | :latin
        | :latvian
        | :lingala
        | :lithuanian
        | :luxembourgish
        | :macedonian
        | :malagasy
        | :malay
        | :malayalam
        | :maltese
        | :maori
        | :marathi
        | :mongolian
        | :nepali
        | :norwegian
        | :odia
        | :oromo
        | :pashto
        | :pidgin
        | :polish
        | :portuguese
        | :punjabi
        | :quechua
        | :romanian
        | :russian
        | :samoan
        | :"scottish-gaelic"
        | :serbian
        | :sesotho
        | :shona
        | :sindhi
        | :sinhala
        | :slovak
        | :slovene
        | :somali
        | :spanish
        | :sundanese
        | :swahili
        | :swedish
        | :tagalog
        | :tajik
        | :tamil
        | :tatar
        | :telugu
        | :thai
        | :tibetan
        | :tigrinya
        | :tongan
        | :tswana
        | :turkish
        | :turkmen
        | :ukrainian
        | :urdu
        | :uyghur
        | :uzbek
        | :vietnamese
        | :welsh
        | :wolof
        | :xhosa
        | :yiddish
        | :yoruba
        | :zulu

      module ForceLanguage
        extend BrandDev::Internal::Type::Enum

        AFRIKAANS: :afrikaans
        ALBANIAN: :albanian
        AMHARIC: :amharic
        ARABIC: :arabic
        ARMENIAN: :armenian
        ASSAMESE: :assamese
        AYMARA: :aymara
        AZERI: :azeri
        BASQUE: :basque
        BELARUSIAN: :belarusian
        BENGALI: :bengali
        BOSNIAN: :bosnian
        BULGARIAN: :bulgarian
        BURMESE: :burmese
        CANTONESE: :cantonese
        CATALAN: :catalan
        CEBUANO: :cebuano
        CHINESE: :chinese
        CORSICAN: :corsican
        CROATIAN: :croatian
        CZECH: :czech
        DANISH: :danish
        DUTCH: :dutch
        ENGLISH: :english
        ESPERANTO: :esperanto
        ESTONIAN: :estonian
        FARSI: :farsi
        FIJIAN: :fijian
        FINNISH: :finnish
        FRENCH: :french
        GALICIAN: :galician
        GEORGIAN: :georgian
        GERMAN: :german
        GREEK: :greek
        GUARANI: :guarani
        GUJARATI: :gujarati
        HAITIAN_CREOLE: :"haitian-creole"
        HAUSA: :hausa
        HAWAIIAN: :hawaiian
        HEBREW: :hebrew
        HINDI: :hindi
        HMONG: :hmong
        HUNGARIAN: :hungarian
        ICELANDIC: :icelandic
        IGBO: :igbo
        INDONESIAN: :indonesian
        IRISH: :irish
        ITALIAN: :italian
        JAPANESE: :japanese
        JAVANESE: :javanese
        KANNADA: :kannada
        KAZAKH: :kazakh
        KHMER: :khmer
        KINYARWANDA: :kinyarwanda
        KOREAN: :korean
        KURDISH: :kurdish
        KYRGYZ: :kyrgyz
        LAO: :lao
        LATIN: :latin
        LATVIAN: :latvian
        LINGALA: :lingala
        LITHUANIAN: :lithuanian
        LUXEMBOURGISH: :luxembourgish
        MACEDONIAN: :macedonian
        MALAGASY: :malagasy
        MALAY: :malay
        MALAYALAM: :malayalam
        MALTESE: :maltese
        MAORI: :maori
        MARATHI: :marathi
        MONGOLIAN: :mongolian
        NEPALI: :nepali
        NORWEGIAN: :norwegian
        ODIA: :odia
        OROMO: :oromo
        PASHTO: :pashto
        PIDGIN: :pidgin
        POLISH: :polish
        PORTUGUESE: :portuguese
        PUNJABI: :punjabi
        QUECHUA: :quechua
        ROMANIAN: :romanian
        RUSSIAN: :russian
        SAMOAN: :samoan
        SCOTTISH_GAELIC: :"scottish-gaelic"
        SERBIAN: :serbian
        SESOTHO: :sesotho
        SHONA: :shona
        SINDHI: :sindhi
        SINHALA: :sinhala
        SLOVAK: :slovak
        SLOVENE: :slovene
        SOMALI: :somali
        SPANISH: :spanish
        SUNDANESE: :sundanese
        SWAHILI: :swahili
        SWEDISH: :swedish
        TAGALOG: :tagalog
        TAJIK: :tajik
        TAMIL: :tamil
        TATAR: :tatar
        TELUGU: :telugu
        THAI: :thai
        TIBETAN: :tibetan
        TIGRINYA: :tigrinya
        TONGAN: :tongan
        TSWANA: :tswana
        TURKISH: :turkish
        TURKMEN: :turkmen
        UKRAINIAN: :ukrainian
        URDU: :urdu
        UYGHUR: :uyghur
        UZBEK: :uzbek
        VIETNAMESE: :vietnamese
        WELSH: :welsh
        WOLOF: :wolof
        XHOSA: :xhosa
        YIDDISH: :yiddish
        YORUBA: :yoruba
        ZULU: :zulu

        def self?.values: -> ::Array[BrandDev::Models::BrandRetrieveByTickerParams::force_language]
      end

      type ticker_exchange =
        :AMEX
        | :AMS
        | :AQS
        | :ASX
        | :ATH
        | :BER
        | :BME
        | :BRU
        | :BSE
        | :BUD
        | :BUE
        | :BVC
        | :CBOE
        | :CNQ
        | :CPH
        | :DFM
        | :DOH
        | :DUB
        | :DUS
        | :DXE
        | :EGX
        | :FSX
        | :HAM
        | :HEL
        | :HKSE
        | :HOSE
        | :ICE
        | :IOB
        | :IST
        | :JKT
        | :JNB
        | :JPX
        | :KLS
        | :KOE
        | :KSC
        | :KUW
        | :LIS
        | :LSE
        | :MCX
        | :MEX
        | :MIL
        | :MUN
        | :NASDAQ
        | :NEO
        | :NSE
        | :NYSE
        | :NZE
        | :OSL
        | :OTC
        | :PAR
        | :PNK
        | :PRA
        | :RIS
        | :SAO
        | :SAU
        | :SES
        | :SET
        | :SGO
        | :SHH
        | :SHZ
        | :SIX
        | :STO
        | :STU
        | :TAI
        | :TAL
        | :TLV
        | :TSX
        | :TSXV
        | :TWO
        | :VIE
        | :WSE
        | :XETRA

      module TickerExchange
        extend BrandDev::Internal::Type::Enum

        AMEX: :AMEX
        AMS: :AMS
        AQS: :AQS
        ASX: :ASX
        ATH: :ATH
        BER: :BER
        BME: :BME
        BRU: :BRU
        BSE: :BSE
        BUD: :BUD
        BUE: :BUE
        BVC: :BVC
        CBOE: :CBOE
        CNQ: :CNQ
        CPH: :CPH
        DFM: :DFM
        DOH: :DOH
        DUB: :DUB
        DUS: :DUS
        DXE: :DXE
        EGX: :EGX
        FSX: :FSX
        HAM: :HAM
        HEL: :HEL
        HKSE: :HKSE
        HOSE: :HOSE
        ICE: :ICE
        IOB: :IOB
        IST: :IST
        JKT: :JKT
        JNB: :JNB
        JPX: :JPX
        KLS: :KLS
        KOE: :KOE
        KSC: :KSC
        KUW: :KUW
        LIS: :LIS
        LSE: :LSE
        MCX: :MCX
        MEX: :MEX
        MIL: :MIL
        MUN: :MUN
        NASDAQ: :NASDAQ
        NEO: :NEO
        NSE: :NSE
        NYSE: :NYSE
        NZE: :NZE
        OSL: :OSL
        OTC: :OTC
        PAR: :PAR
        PNK: :PNK
        PRA: :PRA
        RIS: :RIS
        SAO: :SAO
        SAU: :SAU
        SES: :SES
        SET: :SET
        SGO: :SGO
        SHH: :SHH
        SHZ: :SHZ
        SIX: :SIX
        STO: :STO
        STU: :STU
        TAI: :TAI
        TAL: :TAL
        TLV: :TLV
        TSX: :TSX
        TSXV: :TSXV
        TWO: :TWO
        VIE: :VIE
        WSE: :WSE
        XETRA: :XETRA

        def self?.values: -> ::Array[BrandDev::Models::BrandRetrieveByTickerParams::ticker_exchange]
      end
    end
  end
end
