module BrandDev
  module Models
    type brand_web_scrape_sitemap_params =
      { domain: String } & BrandDev::Internal::Type::request_parameters

    class BrandWebScrapeSitemapParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      def initialize: (
        domain: String,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        request_options: BrandDev::RequestOptions
      }
    end
  end
end
