module BrandDev
  module Models
    type brand_retrieve_naics_response =
      {
        codes: ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code],
        domain: String,
        status: String,
        type: String
      }

    class BrandRetrieveNaicsResponse < BrandDev::Internal::Type::BaseModel
      attr_reader codes: ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code]?

      def codes=: (
        ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code]
      ) -> ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code]

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (
        ?codes: ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code],
        ?domain: String,
        ?status: String,
        ?type: String
      ) -> void

      def to_hash: -> {
        codes: ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code],
        domain: String,
        status: String,
        type: String
      }

      type code =
        {
          code: String,
          confidence: BrandDev::Models::BrandRetrieveNaicsResponse::Code::confidence,
          name: String
        }

      class Code < BrandDev::Internal::Type::BaseModel
        attr_accessor code: String

        attr_accessor confidence: BrandDev::Models::BrandRetrieveNaicsResponse::Code::confidence

        attr_accessor name: String

        def initialize: (
          code: String,
          confidence: BrandDev::Models::BrandRetrieveNaicsResponse::Code::confidence,
          name: String
        ) -> void

        def to_hash: -> {
          code: String,
          confidence: BrandDev::Models::BrandRetrieveNaicsResponse::Code::confidence,
          name: String
        }

        type confidence = :high | :medium | :low

        module Confidence
          extend BrandDev::Internal::Type::Enum

          HIGH: :high
          MEDIUM: :medium
          LOW: :low

          def self?.values: -> ::Array[BrandDev::Models::BrandRetrieveNaicsResponse::Code::confidence]
        end
      end
    end
  end
end
