module BrandDev
  module Models
    type brand_retrieve_naics_params =
      {
        input: String,
        max_results: Integer,
        min_results: Integer,
        timeout_ms: Integer
      }
      & BrandDev::Internal::Type::request_parameters

    class BrandRetrieveNaicsParams < BrandDev::Internal::Type::BaseModel
      extend BrandDev::Internal::Type::RequestParameters::Converter
      include BrandDev::Internal::Type::RequestParameters

      attr_accessor input: String

      attr_reader max_results: Integer?

      def max_results=: (Integer) -> Integer

      attr_reader min_results: Integer?

      def min_results=: (Integer) -> Integer

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        input: String,
        ?max_results: Integer,
        ?min_results: Integer,
        ?timeout_ms: Integer,
        ?request_options: BrandDev::request_opts
      ) -> void

      def to_hash: -> {
        input: String,
        max_results: Integer,
        min_results: Integer,
        timeout_ms: Integer,
        request_options: BrandDev::RequestOptions
      }
    end
  end
end
