module ContextDev
  module Resources
    class AI
      def ai_query: (
        data_to_extract: ::Array[ContextDev::AIAIQueryParams::DataToExtract],
        domain: String,
        ?specific_pages: ContextDev::AIAIQueryParams::SpecificPages,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::AIAIQueryResponse

      def extract_product: (
        url: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::AIExtractProductResponse

      def extract_products: (
        body: ContextDev::Models::AIExtractProductsParams::body,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::AIExtractProductsResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
