module ContextDev
  module Resources
    class Industry
      def retrieve_naics: (
        input: String,
        ?max_results: Integer,
        ?min_results: Integer,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::IndustryRetrieveNaicsResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
