module ContextDev
  module Resources
    class Style
      def extract_fonts: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::StyleExtractFontsResponse

      def extract_styleguide: (
        ?direct_url: String,
        ?domain: String,
        ?prioritize: ContextDev::Models::StyleExtractStyleguideParams::prioritize,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::StyleExtractStyleguideResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
