module ContextDev
  module Resources
    class Utility
      def prefetch: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::UtilityPrefetchResponse

      def prefetch_by_email: (
        email: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::UtilityPrefetchByEmailResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
