module ContextDev
  module Resources
    class Web
      def screenshot: (
        domain: String,
        ?full_screenshot: ContextDev::Models::WebScreenshotParams::full_screenshot,
        ?page: ContextDev::Models::WebScreenshotParams::page,
        ?prioritize: ContextDev::Models::WebScreenshotParams::prioritize,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebScreenshotResponse

      def web_scrape_html: (
        url: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeHTMLResponse

      def web_scrape_images: (
        url: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeImagesResponse

      def web_scrape_md: (
        url: String,
        ?include_images: bool,
        ?include_links: bool,
        ?shorten_base64_images: bool,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeMdResponse

      def web_scrape_sitemap: (
        domain: String,
        ?request_options: ContextDev::request_opts
      ) -> ContextDev::Models::WebWebScrapeSitemapResponse

      def initialize: (client: ContextDev::Client) -> void
    end
  end
end
