module ContextDev
  class AIAIQueryParams = ContextDev::Models::AIAIQueryParams

  class AIExtractProductParams = ContextDev::Models::AIExtractProductParams

  class AIExtractProductsParams = ContextDev::Models::AIExtractProductsParams

  class BrandIdentifyFromTransactionParams = ContextDev::Models::BrandIdentifyFromTransactionParams

  class BrandRetrieveByEmailParams = ContextDev::Models::BrandRetrieveByEmailParams

  class BrandRetrieveByIsinParams = ContextDev::Models::BrandRetrieveByIsinParams

  class BrandRetrieveByNameParams = ContextDev::Models::BrandRetrieveByNameParams

  class BrandRetrieveByTickerParams = ContextDev::Models::BrandRetrieveByTickerParams

  class BrandRetrieveParams = ContextDev::Models::BrandRetrieveParams

  class BrandRetrieveSimplifiedParams = ContextDev::Models::BrandRetrieveSimplifiedParams

  class IndustryRetrieveNaicsParams = ContextDev::Models::IndustryRetrieveNaicsParams

  class StyleExtractFontsParams = ContextDev::Models::StyleExtractFontsParams

  class StyleExtractStyleguideParams = ContextDev::Models::StyleExtractStyleguideParams

  class UtilityPrefetchByEmailParams = ContextDev::Models::UtilityPrefetchByEmailParams

  class UtilityPrefetchParams = ContextDev::Models::UtilityPrefetchParams

  class WebScreenshotParams = ContextDev::Models::WebScreenshotParams

  class WebWebScrapeHTMLParams = ContextDev::Models::WebWebScrapeHTMLParams

  class WebWebScrapeImagesParams = ContextDev::Models::WebWebScrapeImagesParams

  class WebWebScrapeMdParams = ContextDev::Models::WebWebScrapeMdParams

  class WebWebScrapeSitemapParams = ContextDev::Models::WebWebScrapeSitemapParams
end
