module ContextDev
  module Models
    type ai_extract_products_params =
      { body: ContextDev::Models::AIExtractProductsParams::body }
      & ContextDev::Internal::Type::request_parameters

    class AIExtractProductsParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor body: ContextDev::Models::AIExtractProductsParams::body

      def initialize: (
        body: ContextDev::Models::AIExtractProductsParams::body,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        body: ContextDev::Models::AIExtractProductsParams::body,
        request_options: ContextDev::RequestOptions
      }

      type body =
        ContextDev::AIExtractProductsParams::Body::ByDomain
        | ContextDev::AIExtractProductsParams::Body::ByDirectURL

      module Body
        extend ContextDev::Internal::Type::Union

        type by_domain =
          { domain: String, max_products: Integer, timeout_ms: Integer }

        class ByDomain < ContextDev::Internal::Type::BaseModel
          attr_accessor domain: String

          attr_reader max_products: Integer?

          def max_products=: (Integer) -> Integer

          attr_reader timeout_ms: Integer?

          def timeout_ms=: (Integer) -> Integer

          def initialize: (
            domain: String,
            ?max_products: Integer,
            ?timeout_ms: Integer
          ) -> void

          def to_hash: -> {
            domain: String,
            max_products: Integer,
            timeout_ms: Integer
          }
        end

        type by_direct_url =
          { direct_url: String, max_products: Integer, timeout_ms: Integer }

        class ByDirectURL < ContextDev::Internal::Type::BaseModel
          attr_accessor direct_url: String

          attr_reader max_products: Integer?

          def max_products=: (Integer) -> Integer

          attr_reader timeout_ms: Integer?

          def timeout_ms=: (Integer) -> Integer

          def initialize: (
            direct_url: String,
            ?max_products: Integer,
            ?timeout_ms: Integer
          ) -> void

          def to_hash: -> {
            direct_url: String,
            max_products: Integer,
            timeout_ms: Integer
          }
        end

        def self?.variants: -> ::Array[ContextDev::Models::AIExtractProductsParams::body]
      end
    end
  end
end
