module ContextDev
  module Models
    type style_extract_styleguide_response =
      {
        code: Integer,
        domain: String,
        status: String,
        styleguide: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide
      }

    class StyleExtractStyleguideResponse < ContextDev::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader styleguide: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide?

      def styleguide=: (
        ContextDev::Models::StyleExtractStyleguideResponse::Styleguide
      ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide

      def initialize: (
        ?code: Integer,
        ?domain: String,
        ?status: String,
        ?styleguide: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide
      ) -> void

      def to_hash: -> {
        code: Integer,
        domain: String,
        status: String,
        styleguide: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide
      }

      type styleguide =
        {
          colors: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors,
          components: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components,
          element_spacing: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing,
          mode: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode,
          shadows: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows,
          typography: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography
        }

      class Styleguide < ContextDev::Internal::Type::BaseModel
        attr_reader colors: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors?

        def colors=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors

        attr_reader components: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components?

        def components=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components

        attr_reader element_spacing: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing?

        def element_spacing=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing

        attr_reader mode: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode?

        def mode=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode

        attr_reader shadows: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows?

        def shadows=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows

        attr_reader typography: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography?

        def typography=: (
          ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography
        ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography

        def initialize: (
          ?colors: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors,
          ?components: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components,
          ?element_spacing: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing,
          ?mode: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode,
          ?shadows: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows,
          ?typography: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography
        ) -> void

        def to_hash: -> {
          colors: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Colors,
          components: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components,
          element_spacing: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::ElementSpacing,
          mode: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode,
          shadows: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Shadows,
          typography: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography
        }

        type colors = { accent: String, background: String, text: String }

        class Colors < ContextDev::Internal::Type::BaseModel
          attr_reader accent: String?

          def accent=: (String) -> String

          attr_reader background: String?

          def background=: (String) -> String

          attr_reader text: String?

          def text=: (String) -> String

          def initialize: (
            ?accent: String,
            ?background: String,
            ?text: String
          ) -> void

          def to_hash: -> { accent: String, background: String, text: String }
        end

        type components =
          {
            button: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button,
            card: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card
          }

        class Components < ContextDev::Internal::Type::BaseModel
          attr_reader button: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button?

          def button=: (
            ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button
          ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button

          attr_reader card: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card?

          def card=: (
            ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card
          ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card

          def initialize: (
            ?button: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button,
            ?card: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card
          ) -> void

          def to_hash: -> {
            button: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button,
            card: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Card
          }

          type button =
            {
              link: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link,
              primary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              secondary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            }

          class Button < ContextDev::Internal::Type::BaseModel
            attr_reader link: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link?

            def link=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link

            attr_reader primary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary?

            def primary=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary

            attr_reader secondary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary?

            def secondary=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary

            def initialize: (
              ?link: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link,
              ?primary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              ?secondary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            ) -> void

            def to_hash: -> {
              link: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Link,
              primary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Primary,
              secondary: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Components::Button::Secondary
            }

            type link =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }

            class Link < ContextDev::Internal::Type::BaseModel
              attr_reader background_color: String?

              def background_color=: (String) -> String

              attr_reader border_color: String?

              def border_color=: (String) -> String

              attr_reader border_radius: String?

              def border_radius=: (String) -> String

              attr_reader border_style: String?

              def border_style=: (String) -> String

              attr_reader border_width: String?

              def border_width=: (String) -> String

              attr_reader box_shadow: String?

              def box_shadow=: (String) -> String

              attr_reader color: String?

              def color=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader padding: String?

              def padding=: (String) -> String

              attr_reader text_decoration: String?

              def text_decoration=: (String) -> String

              def initialize: (
                ?background_color: String,
                ?border_color: String,
                ?border_radius: String,
                ?border_style: String,
                ?border_width: String,
                ?box_shadow: String,
                ?color: String,
                ?font_size: String,
                ?font_weight: Float,
                ?padding: String,
                ?text_decoration: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }
            end

            type primary =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }

            class Primary < ContextDev::Internal::Type::BaseModel
              attr_reader background_color: String?

              def background_color=: (String) -> String

              attr_reader border_color: String?

              def border_color=: (String) -> String

              attr_reader border_radius: String?

              def border_radius=: (String) -> String

              attr_reader border_style: String?

              def border_style=: (String) -> String

              attr_reader border_width: String?

              def border_width=: (String) -> String

              attr_reader box_shadow: String?

              def box_shadow=: (String) -> String

              attr_reader color: String?

              def color=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader padding: String?

              def padding=: (String) -> String

              attr_reader text_decoration: String?

              def text_decoration=: (String) -> String

              def initialize: (
                ?background_color: String,
                ?border_color: String,
                ?border_radius: String,
                ?border_style: String,
                ?border_width: String,
                ?box_shadow: String,
                ?color: String,
                ?font_size: String,
                ?font_weight: Float,
                ?padding: String,
                ?text_decoration: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }
            end

            type secondary =
              {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }

            class Secondary < ContextDev::Internal::Type::BaseModel
              attr_reader background_color: String?

              def background_color=: (String) -> String

              attr_reader border_color: String?

              def border_color=: (String) -> String

              attr_reader border_radius: String?

              def border_radius=: (String) -> String

              attr_reader border_style: String?

              def border_style=: (String) -> String

              attr_reader border_width: String?

              def border_width=: (String) -> String

              attr_reader box_shadow: String?

              def box_shadow=: (String) -> String

              attr_reader color: String?

              def color=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader padding: String?

              def padding=: (String) -> String

              attr_reader text_decoration: String?

              def text_decoration=: (String) -> String

              def initialize: (
                ?background_color: String,
                ?border_color: String,
                ?border_radius: String,
                ?border_style: String,
                ?border_width: String,
                ?box_shadow: String,
                ?color: String,
                ?font_size: String,
                ?font_weight: Float,
                ?padding: String,
                ?text_decoration: String
              ) -> void

              def to_hash: -> {
                background_color: String,
                border_color: String,
                border_radius: String,
                border_style: String,
                border_width: String,
                box_shadow: String,
                color: String,
                font_size: String,
                font_weight: Float,
                padding: String,
                text_decoration: String
              }
            end
          end

          type card =
            {
              background_color: String,
              border_color: String,
              border_radius: String,
              border_style: String,
              border_width: String,
              box_shadow: String,
              padding: String,
              text_color: String
            }

          class Card < ContextDev::Internal::Type::BaseModel
            attr_reader background_color: String?

            def background_color=: (String) -> String

            attr_reader border_color: String?

            def border_color=: (String) -> String

            attr_reader border_radius: String?

            def border_radius=: (String) -> String

            attr_reader border_style: String?

            def border_style=: (String) -> String

            attr_reader border_width: String?

            def border_width=: (String) -> String

            attr_reader box_shadow: String?

            def box_shadow=: (String) -> String

            attr_reader padding: String?

            def padding=: (String) -> String

            attr_reader text_color: String?

            def text_color=: (String) -> String

            def initialize: (
              ?background_color: String,
              ?border_color: String,
              ?border_radius: String,
              ?border_style: String,
              ?border_width: String,
              ?box_shadow: String,
              ?padding: String,
              ?text_color: String
            ) -> void

            def to_hash: -> {
              background_color: String,
              border_color: String,
              border_radius: String,
              border_style: String,
              border_width: String,
              box_shadow: String,
              padding: String,
              text_color: String
            }
          end
        end

        type element_spacing =
          { lg: String, md: String, sm: String, xl: String, xs: String }

        class ElementSpacing < ContextDev::Internal::Type::BaseModel
          attr_reader lg: String?

          def lg=: (String) -> String

          attr_reader md: String?

          def md=: (String) -> String

          attr_reader sm: String?

          def sm=: (String) -> String

          attr_reader xl: String?

          def xl=: (String) -> String

          attr_reader xs: String?

          def xs=: (String) -> String

          def initialize: (
            ?lg: String,
            ?md: String,
            ?sm: String,
            ?xl: String,
            ?xs: String
          ) -> void

          def to_hash: -> {
            lg: String,
            md: String,
            sm: String,
            xl: String,
            xs: String
          }
        end

        type mode = :light | :dark

        module Mode
          extend ContextDev::Internal::Type::Enum

          LIGHT: :light
          DARK: :dark

          def self?.values: -> ::Array[ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::mode]
        end

        type shadows =
          { inner: String, lg: String, md: String, sm: String, xl: String }

        class Shadows < ContextDev::Internal::Type::BaseModel
          attr_reader inner: String?

          def inner=: (String) -> String

          attr_reader lg: String?

          def lg=: (String) -> String

          attr_reader md: String?

          def md=: (String) -> String

          attr_reader sm: String?

          def sm=: (String) -> String

          attr_reader xl: String?

          def xl=: (String) -> String

          def initialize: (
            ?inner: String,
            ?lg: String,
            ?md: String,
            ?sm: String,
            ?xl: String
          ) -> void

          def to_hash: -> {
            inner: String,
            lg: String,
            md: String,
            sm: String,
            xl: String
          }
        end

        type typography =
          {
            headings: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings,
            p_: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P
          }

        class Typography < ContextDev::Internal::Type::BaseModel
          attr_reader headings: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings?

          def headings=: (
            ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings
          ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings

          attr_reader p_: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P?

          def p_=: (
            ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P
          ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P

          def initialize: (
            ?headings: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings,
            ?p_: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P
          ) -> void

          def to_hash: -> {
            headings: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings,
            p_: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::P
          }

          type headings =
            {
              :h1 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              :h2 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              :h3 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              :h4 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            }

          class Headings < ContextDev::Internal::Type::BaseModel
            attr_reader h1: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1?

            def h1=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1

            attr_reader h2: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2?

            def h2=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2

            attr_reader h3: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3?

            def h3=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3

            attr_reader h4: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4?

            def h4=: (
              ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            ) -> ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4

            def initialize: (
              ?h1: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              ?h2: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              ?h3: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              ?h4: ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            ) -> void

            def to_hash: -> {
              :h1 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H1,
              :h2 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H2,
              :h3 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H3,
              :h4 => ContextDev::Models::StyleExtractStyleguideResponse::Styleguide::Typography::Headings::H4
            }

            type h1 =
              {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H1 < ContextDev::Internal::Type::BaseModel
              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader letter_spacing: String?

              def letter_spacing=: (String) -> String

              attr_reader line_height: String?

              def line_height=: (String) -> String

              def initialize: (
                ?font_family: String,
                ?font_size: String,
                ?font_weight: Float,
                ?letter_spacing: String,
                ?line_height: String
              ) -> void

              def to_hash: -> {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h2 =
              {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H2 < ContextDev::Internal::Type::BaseModel
              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader letter_spacing: String?

              def letter_spacing=: (String) -> String

              attr_reader line_height: String?

              def line_height=: (String) -> String

              def initialize: (
                ?font_family: String,
                ?font_size: String,
                ?font_weight: Float,
                ?letter_spacing: String,
                ?line_height: String
              ) -> void

              def to_hash: -> {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h3 =
              {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H3 < ContextDev::Internal::Type::BaseModel
              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader letter_spacing: String?

              def letter_spacing=: (String) -> String

              attr_reader line_height: String?

              def line_height=: (String) -> String

              def initialize: (
                ?font_family: String,
                ?font_size: String,
                ?font_weight: Float,
                ?letter_spacing: String,
                ?line_height: String
              ) -> void

              def to_hash: -> {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end

            type h4 =
              {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }

            class H4 < ContextDev::Internal::Type::BaseModel
              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_reader font_weight: Float?

              def font_weight=: (Float) -> Float

              attr_reader letter_spacing: String?

              def letter_spacing=: (String) -> String

              attr_reader line_height: String?

              def line_height=: (String) -> String

              def initialize: (
                ?font_family: String,
                ?font_size: String,
                ?font_weight: Float,
                ?letter_spacing: String,
                ?line_height: String
              ) -> void

              def to_hash: -> {
                font_family: String,
                font_size: String,
                font_weight: Float,
                letter_spacing: String,
                line_height: String
              }
            end
          end

          type p_ =
            {
              font_family: String,
              font_size: String,
              font_weight: Float,
              letter_spacing: String,
              line_height: String
            }

          class P < ContextDev::Internal::Type::BaseModel
            attr_reader font_family: String?

            def font_family=: (String) -> String

            attr_reader font_size: String?

            def font_size=: (String) -> String

            attr_reader font_weight: Float?

            def font_weight=: (Float) -> Float

            attr_reader letter_spacing: String?

            def letter_spacing=: (String) -> String

            attr_reader line_height: String?

            def line_height=: (String) -> String

            def initialize: (
              ?font_family: String,
              ?font_size: String,
              ?font_weight: Float,
              ?letter_spacing: String,
              ?line_height: String
            ) -> void

            def to_hash: -> {
              font_family: String,
              font_size: String,
              font_weight: Float,
              letter_spacing: String,
              line_height: String
            }
          end
        end
      end
    end
  end
end
