module ContextDev
  module Models
    type style_extract_styleguide_params =
      {
        direct_url: String,
        domain: String,
        prioritize: ContextDev::Models::StyleExtractStyleguideParams::prioritize,
        timeout_ms: Integer
      }
      & ContextDev::Internal::Type::request_parameters

    class StyleExtractStyleguideParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_reader direct_url: String?

      def direct_url=: (String) -> String

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader prioritize: ContextDev::Models::StyleExtractStyleguideParams::prioritize?

      def prioritize=: (
        ContextDev::Models::StyleExtractStyleguideParams::prioritize
      ) -> ContextDev::Models::StyleExtractStyleguideParams::prioritize

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        ?direct_url: String,
        ?domain: String,
        ?prioritize: ContextDev::Models::StyleExtractStyleguideParams::prioritize,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        direct_url: String,
        domain: String,
        prioritize: ContextDev::Models::StyleExtractStyleguideParams::prioritize,
        timeout_ms: Integer,
        request_options: ContextDev::RequestOptions
      }

      type prioritize = :speed | :quality

      module Prioritize
        extend ContextDev::Internal::Type::Enum

        SPEED: :speed
        QUALITY: :quality

        def self?.values: -> ::Array[ContextDev::Models::StyleExtractStyleguideParams::prioritize]
      end
    end
  end
end
