module ContextDev
  module Models
    type utility_prefetch_params =
      { domain: String, timeout_ms: Integer }
      & ContextDev::Internal::Type::request_parameters

    class UtilityPrefetchParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      attr_reader timeout_ms: Integer?

      def timeout_ms=: (Integer) -> Integer

      def initialize: (
        domain: String,
        ?timeout_ms: Integer,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        timeout_ms: Integer,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
