module ContextDev
  module Models
    type web_web_scrape_sitemap_params =
      { domain: String } & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeSitemapParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor domain: String

      def initialize: (
        domain: String,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        domain: String,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
