module ContextDev
  module Models
    type web_web_scrape_md_response =
      {
        markdown: String,
        success: ContextDev::Models::WebWebScrapeMdResponse::success,
        url: String
      }

    class WebWebScrapeMdResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor markdown: String

      attr_accessor success: ContextDev::Models::WebWebScrapeMdResponse::success

      attr_accessor url: String

      def initialize: (
        markdown: String,
        success: ContextDev::Models::WebWebScrapeMdResponse::success,
        url: String
      ) -> void

      def to_hash: -> {
        markdown: String,
        success: ContextDev::Models::WebWebScrapeMdResponse::success,
        url: String
      }

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeMdResponse::success]
      end
    end
  end
end
