module ContextDev
  module Models
    type web_screenshot_response =
      {
        code: Integer,
        domain: String,
        screenshot: String,
        screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        status: String
      }

    class WebScreenshotResponse < ContextDev::Internal::Type::BaseModel
      attr_reader code: Integer?

      def code=: (Integer) -> Integer

      attr_reader domain: String?

      def domain=: (String) -> String

      attr_reader screenshot: String?

      def screenshot=: (String) -> String

      attr_reader screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type?

      def screenshot_type=: (
        ContextDev::Models::WebScreenshotResponse::screenshot_type
      ) -> ContextDev::Models::WebScreenshotResponse::screenshot_type

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?code: Integer,
        ?domain: String,
        ?screenshot: String,
        ?screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        ?status: String
      ) -> void

      def to_hash: -> {
        code: Integer,
        domain: String,
        screenshot: String,
        screenshot_type: ContextDev::Models::WebScreenshotResponse::screenshot_type,
        status: String
      }

      type screenshot_type = :viewport | :fullPage

      module ScreenshotType
        extend ContextDev::Internal::Type::Enum

        VIEWPORT: :viewport
        FULL_PAGE: :fullPage

        def self?.values: -> ::Array[ContextDev::Models::WebScreenshotResponse::screenshot_type]
      end
    end
  end
end
