module ContextDev
  module Models
    type web_web_scrape_html_response =
      {
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        url: String
      }

    class WebWebScrapeHTMLResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor html: String

      attr_accessor success: ContextDev::Models::WebWebScrapeHTMLResponse::success

      attr_accessor url: String

      def initialize: (
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        url: String
      ) -> void

      def to_hash: -> {
        html: String,
        success: ContextDev::Models::WebWebScrapeHTMLResponse::success,
        url: String
      }

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeHTMLResponse::success]
      end
    end
  end
end
