module ContextDev
  module Models
    type web_web_scrape_images_response =
      {
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      }

    class WebWebScrapeImagesResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image]

      attr_accessor success: ContextDev::Models::WebWebScrapeImagesResponse::success

      attr_accessor url: String

      def initialize: (
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      ) -> void

      def to_hash: -> {
        images: ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image],
        success: ContextDev::Models::WebWebScrapeImagesResponse::success,
        url: String
      }

      type image =
        {
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_
        }

      class Image < ContextDev::Internal::Type::BaseModel
        attr_accessor alt: String?

        attr_accessor element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element

        attr_accessor src: String

        attr_accessor type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_

        def initialize: (
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_
        ) -> void

        def to_hash: -> {
          alt: String?,
          element: ContextDev::Models::WebWebScrapeImagesResponse::Image::element,
          src: String,
          type: ContextDev::Models::WebWebScrapeImagesResponse::Image::type_
        }

        type element = :img | :svg | :link | :source | :video

        module Element
          extend ContextDev::Internal::Type::Enum

          IMG: :img
          SVG: :svg
          LINK: :link
          SOURCE: :source
          VIDEO: :video

          def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image::element]
        end

        type type_ = :url | :html | :base64

        module Type
          extend ContextDev::Internal::Type::Enum

          URL: :url
          HTML: :html
          BASE64: :base64

          def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::Image::type_]
        end
      end

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeImagesResponse::success]
      end
    end
  end
end
