module ContextDev
  module Models
    type web_web_scrape_html_params =
      { url: String } & ContextDev::Internal::Type::request_parameters

    class WebWebScrapeHTMLParams < ContextDev::Internal::Type::BaseModel
      extend ContextDev::Internal::Type::RequestParameters::Converter
      include ContextDev::Internal::Type::RequestParameters

      attr_accessor url: String

      def initialize: (
        url: String,
        ?request_options: ContextDev::request_opts
      ) -> void

      def to_hash: -> {
        url: String,
        request_options: ContextDev::RequestOptions
      }
    end
  end
end
