module ContextDev
  module Models
    type web_web_scrape_sitemap_response =
      {
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String]
      }

    class WebWebScrapeSitemapResponse < ContextDev::Internal::Type::BaseModel
      attr_accessor domain: String

      attr_accessor meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta

      attr_accessor success: ContextDev::Models::WebWebScrapeSitemapResponse::success

      attr_accessor urls: ::Array[String]

      def initialize: (
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String]
      ) -> void

      def to_hash: -> {
        domain: String,
        meta: ContextDev::Models::WebWebScrapeSitemapResponse::Meta,
        success: ContextDev::Models::WebWebScrapeSitemapResponse::success,
        urls: ::Array[String]
      }

      type meta =
        {
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        }

      class Meta < ContextDev::Internal::Type::BaseModel
        attr_accessor errors: Integer

        attr_accessor sitemaps_discovered: Integer

        attr_accessor sitemaps_fetched: Integer

        attr_accessor sitemaps_skipped: Integer

        def initialize: (
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        ) -> void

        def to_hash: -> {
          errors: Integer,
          sitemaps_discovered: Integer,
          sitemaps_fetched: Integer,
          sitemaps_skipped: Integer
        }
      end

      type success = true

      module Success
        extend ContextDev::Internal::Type::Enum

        TRUE: true

        def self?.values: -> ::Array[ContextDev::Models::WebWebScrapeSitemapResponse::success]
      end
    end
  end
end
